# Generated by Django 5.1.7 on 2025-03-17 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_medicine', models.CharField(max_length=150)),
                ('periodicity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(24)])),
                ('duration', models.CharField(max_length=50)),
                ('user_id', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
