# Generated by Django 5.1.7 on 2025-03-18 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='periodicity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
